### ISSUE TITLE
compile with clang

### ISSUE THREAD

**Issue by HolgerJeromin** [acplt/rte#12]
Right now every compile call is gcc instead of CC. 
So a compile on travis does not really compile with clang, or does it?
https://travis-ci.org/acplt/rte/builds/108598309

**Comment by Stasik0** [comment]
Should be fixable in makmak

**Comment by HolgerJeromin** [comment]
The normal linux makefile sets compiler to GCC. this has to be changed on the fly.
Dont forget the makefiles for ov (which are hardcoded).

**Comment by Stasik0** [comment]
PRs are always welcome

**Comment by Stasik0** [comment]
@HolgerJeromin regarding compiling libraries, on my box ```make CC=clang``` works

**Comment by HolgerJeromin** [comment]
>  this overrides the line...

i am surprised. Why is that?

**Comment by Stasik0** [comment]
Makefile semantics, variables that are passed to make directly "bind" stronger than built-in variables

**Comment by LEvertz** [comment]
The "Hard set" to GCC  @HolgerJeromin  referred to is only to choose the right *.mk file. For compilation a CC-Variable is used.
