### ISSUE TITLE
HMI Bug

### ISSUE THREAD

**Issue by hfaham** [acplt/rte#27]
when RebuildObject in HMI is called, an error is encountered when using "Datatables" library.
My first doubt is that the sourceOfLibraries in the Blackbox are not imported in the correct order.
Another thing I noticed that the dimensions of the figures in the graphPlotter template keep on constantly changing if RebuildObject is executed.

**Comment by HolgerJeromin** [comment]
`sourceOfLibrary` is guaranteed to be included [only once](https://github.com/acplt/rte/blob/d93f2c062870d72eec7ee94906e985b888dbaf53/addonlibs/hmi/hmiJavaScript/JavaScript/hmi-hub-loader.js#L138).
So when calling `RebuildObject` on an `blackbox` the JS files are not included again.

**Comment by hfaham** [comment]
somehow after reloading, the library is no longer available, because everytime i execute a predefined function from these libraries the browser does not recognize it. 

My guess was based on the most common cause for this error (according to the datatable forum from jquery) which is the libraries sequence, and when i tried changing the libraries sequence in the sourceOFLibrary i get the same error. However what you wrote makes sense,  I am quite confused now what could the cause for this error be.

**Comment by hfaham** [comment]
@HolgerJeromin I just check the loop where the existing libraries are checked if they were already loaded in browser which you mentioned above, I have commented the splice command and incremented the counter to bypass this while loop (as a test if I will not be getting the same error) and this actually worked.. What I am currently doubting is that the libraries I am loading are dependent on one another and when they are already loaded in the browser they seem to be asynchoronously initialized which causes that crash. What do you think?

**Comment by HolgerJeromin** [comment]
This is weird. I know of no way to get rid of loaded JS code in browsers :-)

You have to step in with a debugger. I am a fan of the integrated chrome debugger. 

If you want i can have look tomorrow via [teamviewer](https://www.teamviewer.com/de/). You can call me via mobile phone between 10 and 17 o'clock.

**Comment by hfaham** [comment]
sounds like a good deal will call you tomorrow then :) Thanks!

**Comment by HolgerJeromin** [comment]
You should add a fresh staticdisplaycomponent.fbd to the cshmi library

**Comment by hfaham** [comment]
will do in a couple of days. Thanks :)
