### ISSUE TITLE
HMI: Handle setting visible on parents of Blackbox

### ISSUE THREAD

**Issue by HolgerJeromin** [acplt/rte#30]
Setting visible is special. We set style to display:none or block which is valid for the whole tree. But this does not catch Blackbox.  For Blackbox handling we just have to iterate similar to the code of #28 and change the display style, too.

**Comment by HolgerJeromin** [comment]
Changes in X and y should behave same.

**Comment by hfaham** [comment]
Maybe that can be fixed by iterating with _interpreteChildrensRecursive under
 _buildSvgGroup and toggle the visibility according to the group visibility? Would that be the right thing to do?

**Comment by HolgerJeromin** [comment]
`_interpreteChildrensRecursive` is kind of compile. It does not loop through the current children, but builds up new children

**Comment by hfaham** [comment]
Okay... So I have been trying to trace where the visibility is toggled and I wanted to share with you my results before I start changing things around..

in hmi-class-cshmi 
[VisualObject.setAttribute](https://github.com/acplt/rte/blob/master/addonlibs/hmi/hmiJavaScript/JavaScript/hmi-class-cshmi.js#L1932), I should basically check if the visualobject is a blackbox then iterate the blackbox elements and hide them.

**Comment by hfaham** [comment]
@HolgerJeromin Was just writing here :) :)

**Comment by HolgerJeromin** [comment]
I am pretty sure my current fix from #31 handles all cases.

**Comment by HolgerJeromin** [comment]
css display:none removes all childrens, so no iteration is needed here. But with every change in x, y or visible we could have a blackbox child which has to moved around or hidden.

**Comment by hfaham** [comment]
Calling the [VisualObject.classList](https://github.com/acplt/rte/pull/31/files#diff-e72f63b54f46efe501931bfad428814dR1947) returns an empty array which causes the code to skip the blackbox visibility toggle for loop that follows up.

**Comment by HolgerJeromin** [comment]
In any case? This surprises me. Perhaps we need another Teamviewer session :-)

**Comment by hfaham** [comment]
Sounds good when can you?

**Comment by HolgerJeromin** [comment]
You can call me tomorrow between 9:30 and 16:00 oclock
