### ISSUE TITLE
Functionblock typemethod durch http

### ISSUE THREAD

**Issue by zzzdeb** [acplt/rte#37]
Typemethod wird nicht aufgerufen, obwohl iexreq=true und actimode=1 gesetzt werden.

**Comment by HolgerJeromin** [comment]
Ist der Baustein in einer Taskliste eingehängt?

**Comment by zzzdeb** [comment]
genau diese typemethod wird aufgerufen, wenn activemode und iexreq durch ifbspro geändert werden.
ich habe keine tiefe kenntnisse. soll ich zusätzlich was tun, um mit http gleiche resultate wie mit ifbspro  zu erhalten?

**Comment by HolgerJeromin** [comment]
Oh, habe das Stichwort "http" übersehen. Geht auch:
`/setVar?path=/TechUnits/add1.actimode&newvalue=3`
Siehe Definition von actimode:
https://github.com/acplt/rte/blob/37c99c1de2a85f22622903acc2fd22280176aec7/syslibs/functionblock/fb/model/fb.ovm#L103
3 führt also die typemethod genau einmal aus.

**Comment by zzzdeb** [comment]
Danke. 
Sorry, ich habe versehen.
Ich habe festgestellt, dass dieses Problem bei den Objekten auftritt, die durch http erstellt wurden.

**Comment by HolgerJeromin** [comment]
> Ist der Baustein in einer Taskliste eingehängt?

Ist dies wirklich der Fall?

/link?path=/TechUnits/add1.taskparent&element=/UrTask

Fehlt wahrscheinlich...

**Comment by zzzdeb** [comment]
Es hat wirklich geklappt. Danke sehr.
