### ISSUE TITLE
ks vs ov

### ISSUE THREAD

**Issue by zzzdeb** [acplt/rte#42]
ks_logfile.h vs ov_logfile.h
KS_VAR_TYPE vs OV_VAR_TYPE
etc....
kann mir bitte jemand erklären, wann ich welchen anwenden soll? Sie scheinen genau dasgleiche zu tun.

**Comment by HolgerJeromin** [comment]
Ja, alle KS Defines/Funktionen sind Kopien der OV Varianten. Daher ist es "egal", welche du nutzt. 
Vorgesehen ist es, wenn man im KS Kontext arbeitet (wirst du wohl nicht tun, tun aber die [KS libs](https://github.com/acplt/rte/tree/d93f2c062870d72eec7ee94906e985b888dbaf53/syslibs/comm)), die KS Defines/Funktionen zu nutzen und wenn du mit OV Objekten arbeitest (wahrscheinlich), die OV Defines/Funktionen.

https://github.com/acplt/rte/blob/d93f2c062870d72eec7ee94906e985b888dbaf53/syslibs/comm/ksbase/include/ov_ksserver_backend.h#L72-L114

**Comment by zzzdeb** [comment]
danke
