### ISSUE TITLE
OPC UA interface service in RTE does not automatically restart.

### ISSUE THREAD

**Issue by antony-liu** [acplt/rte#56]
Problem description (tested on Ubuntu 16, 64bit):

- Follow the [instructions](https://github.com/acplt/openAAS_workshop#setting-up-the-server) to start a server
- Create the generic OPC UA Interface via web interface (Browser): http://localhost:7509/createObject?format=tcl&factory=/acplt/opcua/uaServer&path=/TechUnits/opcuaInterface
- Explorer the server With uaExpert 
- Stop the server and restart it.

After restarting, OPC UA Service is not started. Is it not automatically restarted? How to make it automatically restart.

**Comment by FlorianPalm** [comment]
A restart is not available in that version. There is a workaround if you export your data to an FBD file before you shutdown the server and reload it.

**Comment by antony-liu** [comment]
It works, thanks a lot.
