### ISSUE TITLE
fix tasklist structure

### ISSUE THREAD

**Issue by LarsNt** [acplt/rte#59]
When calling fb tasks form c code it is possible to create loops, which cause the server to crash.
To avoid this, execution should be triggered by the tasklist association.
In places where this is not possible (due to limitations of the concept) it is imperative to check that no loops exist.

Timed function blocks in vdivde3696 library are broken because of this as they cannot get the cycle time from the `UrTask`.

**Comment by mhthies** [comment]
Closed by merging #60
